=== LindaLi89/kuni/BoardView/bin/xml/XML_Beispiel_Daten/Spielfeld.dtd
<!ENTITY % verteilungAttribut "zufaellig|gleichmaessig|symmetrisch" >
<!ENTITY % koordinaten "PositionX, PositionY" >
<!ENTITY % attribute
	"min CDATA #REQUIRED 
	max CDATA #REQUIRED
    verteilung (%verteilungAttribut;) #REQUIRED" >



<!ELEMENT Spielfeld  ( Leafs, Mushrooms, Trees, Mouse*, Goal)>
<!ATTLIST Spielfeld 
    height CDATA #REQUIRED
    width CDATA #REQUIRED
    randomMushrooms (yes|no) #REQUIRED>

<!ELEMENT Leafs  ( Leaf* )>
<!ATTLIST Leafs %attribute;>
<!ELEMENT Leaf  ( %koordinaten; )>

<!ELEMENT Mushrooms  ( Mushroom* )>
<!ATTLIST Mushrooms %attribute;>
<!ELEMENT Mushroom  ( %koordinaten; )>  
 
<!ELEMENT Trees  ( Tree* )>
<!ATTLIST Trees %attribute;>
<!ELEMENT Tree  ( %koordinaten; )>

<!ELEMENT Mouse ( %koordinaten; )> 

<!ELEMENT Goal ( %koordinaten; )>

<!ELEMENT PositionX  ( #PCDATA )>
<!ELEMENT PositionY  ( #PCDATA )>

=== LindaLi89/kuni/BoardView/src/xml/XML_Beispiel_Daten/Garten 7.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Spielfeld SYSTEM "Spielfeld.dtd">

<Spielfeld height="9" width="9" randomMushrooms="no">
    <Leafs min="16" max="16" verteilung="zufaellig">
        <Leaf>
            <PositionX>4</PositionX>
            <PositionY>2</PositionY>
        </Leaf>
        <Leaf>
    		<PositionX>5</PositionX>
    		<PositionY>2</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>6</PositionX>
    		<PositionY>2</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>3</PositionX>
    		<PositionY>3</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>4</PositionX>
    		<PositionY>3</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>5</PositionX>
    		<PositionY>3</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>6</PositionX>
    		<PositionY>3</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>2</PositionX>
    		<PositionY>4</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>3</PositionX>
    		<PositionY>4</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>4</PositionX>
    		<PositionY>4</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>5</PositionX>
    		<PositionY>4</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>6</PositionX>
    		<PositionY>4</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>3</PositionX>
    		<PositionY>5</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>4</PositionX>
    		<PositionY>5</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>2</PositionX>
    		<PositionY>6</PositionY>
    	</Leaf>
    	<Leaf>
    		<PositionX>3</PositionX>
    		<PositionY>6</PositionY>
    	</Leaf>
    </Leafs>
    <Mushrooms min="1" max="1" verteilung="zufaellig">
    	<Mushroom>
    		<PositionX>1</PositionX>
    		<PositionY>0</PositionY>
    	</Mushroom>
    </Mushrooms>
    <Trees min="17" max="17" verteilung="zufaellig">
    	<Tree>
    		<PositionX>4</PositionX>
    		<PositionY>1</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>5</PositionX>
    		<PositionY>1</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>6</PositionX>
    		<PositionY>1</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>7</PositionX>
    		<PositionY>1</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>7</PositionX>
    		<PositionY>2</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>7</PositionX>
    		<PositionY>3</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>6</PositionX>
    		<PositionY>5</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>5</PositionX>
    		<PositionY>5</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>4</PositionX>
    		<PositionY>6</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>4</PositionX>
    		<PositionY>7</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>3</PositionX>
    		<PositionY>7</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>2</PositionX>
    		<PositionY>7</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>1</PositionX>
    		<PositionY>6</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>2</PositionX>
    		<PositionY>5</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>1</PositionX>
    		<PositionY>4</PositionY>
    	</Tree>
    	   	<Tree>
    		<PositionX>2</PositionX>
    		<PositionY>3</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>3</PositionX>
    		<PositionY>2</PositionY>
    	</Tree>
    	<Tree>
    		<PositionX>7</PositionX>
    		<PositionY>4</PositionY>
    	</Tree>
    </Trees>
     <Mouse>
    		<PositionX>8</PositionX>
    		<PositionY>3</PositionY>
    </Mouse>
     <Goal>
    	<PositionX>8</PositionX>
    	<PositionY>2</PositionY>
    </Goal>
</Spielfeld>

=== LindaLi89/kuni/BoardView/src/xml/XML_Beispiel_Daten/gemischt.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Spielfeld SYSTEM "Spielfeld.dtd">

<Spielfeld height="10" width="7" randomMushrooms="yes">
    <Leafs min="5" max="5" verteilung="gleichmaessig">
        <Leaf>
            <PositionX>4</PositionX>
            <PositionY>5</PositionY>
        </Leaf>
        <Leaf>
            <PositionX>5</PositionX>
            <PositionY>3</PositionY>
        </Leaf>
    </Leafs>
    <Mushrooms min="4" max="5" verteilung="gleichmaessig">
        <Mushroom>
            <PositionX>6</PositionX>
            <PositionY>5</PositionY>
        </Mushroom>
        <Mushroom>
            <PositionX>6</PositionX>
            <PositionY>1</PositionY>
        </Mushroom>
    </Mushrooms>
    
    <Trees min="4" max="5" verteilung="gleichmaessig"> </Trees>
</Spielfeld>

=== LindaLi89/kuni/BoardView/src/xml/XML_Beispiel_Daten/KoordinatenSetzen.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Spielfeld SYSTEM "Spielfeld.dtd">

<Spielfeld height="10" width="7" randomMushrooms="no">
    <Leafs min="3" max="5" verteilung="zufaellig">
        <Leaf>
            <PositionX>4</PositionX>
            <PositionY>5</PositionY>
        </Leaf>
        <Leaf>
            <PositionX>5</PositionX>
            <PositionY>3</PositionY>
        </Leaf>
    </Leafs>
    <Mushrooms min="3" max="5" verteilung="symmetrisch">
        <Mushroom>
            <PositionX>6</PositionX>
            <PositionY>5</PositionY>
        </Mushroom>
        <Mushroom>
            <PositionX>6</PositionX>
            <PositionY>1</PositionY>
        </Mushroom>
    </Mushrooms>
    <Trees min="5" max="9" verteilung="gleichmaessig">
        <Tree>
            <PositionX>4</PositionX>
            <PositionY>4</PositionY>
        </Tree>
        <Tree>
            <PositionX>3</PositionX>
            <PositionY>2</PositionY>
        </Tree>
        <Tree>
            <PositionX>8</PositionX>
            <PositionY>8</PositionY>
        </Tree>
 
    </Trees>
     <Mouse>
    		<PositionX>0</PositionX>
    		<PositionY>0</PositionY>
    </Mouse>
</Spielfeld>

=== LindaLi89/kuni/BoardView/bin/xml/XML_Beispiel_Daten/9X9.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Spielfeld SYSTEM "Spielfeld.dtd">

<Spielfeld height="10" width="10" randomMushrooms="no">
    <Leafs min="5" max="15" verteilung="zufaellig">
        <Leaf>
            <PositionX>4</PositionX>
            <PositionY>5</PositionY>
        </Leaf>
        <Leaf>
            <PositionX>5</PositionX>
            <PositionY>3</PositionY>
        </Leaf>
    </Leafs>
    <Mushrooms min="4" max="15" verteilung="zufaellig">
        <Mushroom>
            <PositionX>6</PositionX>
            <PositionY>5</PositionY>
        </Mushroom>
        <Mushroom>
            <PositionX>6</PositionX>
            <PositionY>1</PositionY>
        </Mushroom>
    </Mushrooms>
    
    <Trees min="4" max="15" verteilung="zufaellig"> </Trees>
    <Mouse>
    		<PositionX>0</PositionX>
    		<PositionY>1</PositionY>
    </Mouse>
</Spielfeld>

=== LindaLi89/kuni/BoardView/src/xml/XML_Beispiel_Daten/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Spielfeld SYSTEM "Spielfeld.dtd">

<Spielfeld height="2" width="3" randomMushrooms="no">
    <Leafs min="4" max="4" verteilung="zufaellig">
        <Leaf>
            <PositionX>0</PositionX>
            <PositionY>0</PositionY>
        </Leaf>
        <Leaf>
            <PositionX>0</PositionX>
            <PositionY>1</PositionY>
        </Leaf>
        <Leaf>
            <PositionX>0</PositionX>
            <PositionY>1</PositionY>
        </Leaf>
        <Leaf>
            <PositionX>2</PositionX>
            <PositionY>1</PositionY>
        </Leaf>
    </Leafs>
    <Mushrooms min="0" max="0" verteilung="symmetrisch"> </Mushrooms>
    <Trees min="0" max="0" verteilung="gleichmaessig"> </Trees>
</Spielfeld>

=== LindaLi89/kuni/BoardView/src/xml/XML_Beispiel_Daten/Garten 1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Spielfeld SYSTEM "Spielfeld.dtd">

<Spielfeld height="1" width="8" randomMushrooms="no">
    <Leafs min="1" max="1" verteilung="zufaellig">
        <Leaf>
            <PositionX>3</PositionX>
            <PositionY>0</PositionY>
        </Leaf>
        <Leaf>
            <PositionX>5</PositionX>
            <PositionY>0</PositionY>
        </Leaf>
        <Leaf>
            <PositionX>7</PositionX>
            <PositionY>0</PositionY>
        </Leaf>
    </Leafs>
    <Mushrooms min="0" max="0" verteilung="zufaellig"></Mushrooms>
    <Trees min="0" max="0" verteilung="zufaellig"></Trees>
    <Mouse>
    	<PositionX>0</PositionX>
    	<PositionY>0</PositionY>
    </Mouse>
    <Goal>
    	<PositionX>7</PositionX>
    	<PositionY>0</PositionY>
    </Goal>
</Spielfeld>
